### PR TITLE
Changing the notification library

### PR DESCRIPTION
**Pull request by jaiminkhanderia**
Resolved the error of using pynotify by changing it to use the notify2 library

### CODE REVIEW

**Comment by an00bhav** [comment]
@jaiminkhanderia Awesome! I will check it on my development environment and let you know here. Thanks.

**Comment by jaiminkhanderia** [comment]
@neo1691 Yes, I have tried it on Ubuntu and it works. Still I feel it would be better for you to check it.
Thanks

**Comment by an00bhav** [comment]
I’m looking for a library that works seamlessly across all platforms. (
Windows, Linux, Mac). I have a mac and will check on that.

**Comment by jaiminkhanderia** [comment]
Alright, let me know after checking if there any changes to be made
Thanks

**Comment by harsham4026** [comment]
@jaiminkhanderia I tried with this library but it was not working on all the platforms. And @neo1691 notify-send was also not working all the platforms.

The issue I was facing using notify2 and ran following commands
>>> import notify2
>>> notify2.init("Scorer")

dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NoMemory: Not enough memory

**Comment by jaiminkhanderia** [comment]
@harsham4026 Alright, thanks I'll check and let you know if there is something that works on all platforms

**Comment by an00bhav** [comment]
@jaiminkhanderia @harsham4026 Sorry for the inactivity here. I have been travelling for my vacations in a different timezone without a lot of internet. Starting today I plan to pick up things where I left. Thank you for your help. 

Any update on this PR? Did you find something that works on all the platforms? If not I think it's safe to close this PR for now. 

Thoughts?

**Comment by harsham4026** [comment]
@neo1691 I was exploring about it but couldn't find the one which works for all the platforms though :)

**Comment by jaiminkhanderia** [comment]
@neo1691 @harsham4026 I too was exploring other libraries(plyer, ntfy) but none of them seem to work on Mac and so I haven't been able to find one which works on all platforms

**Review by Sandhya023 — APPROVED** [review]

**Review by Sandhya023 — APPROVED** [review]

**Comment by an00bhav** [comment]
@jaiminkhanderia Okay thanks for your help. Let's close this PR for now and think about a library that works for all platforms seamlessly.

**Comment by jaiminkhanderia** [comment]
@neo1691 Alright, I'll look for libraries and let you know if I find anything that works for all platforms

**Pull request closed without merging**
