### PR TITLE
Uisupport

### PR DESCRIPTION
**Pull request by nirmalvp**
Fixed the error due to the merge conflict with the previous PR.The quit option is displayed now

### CODE REVIEW

**Comment by neo1691** [comment]
I think that happened because of my error. Thanks for fixing it.

**Comment by nirmalvp** [comment]
What do you think about the new UI? do you think we should have sections within it for user configuration rather than the command line args. I don't know which one is a cleaner approach

**Comment by neo1691** [comment]
The new UI is great, it's for user interested not much interested with the command line options. I think we can create two versions on which this script is run:

1) interactive mode: Which which show your UI and other options to configure it: We can very well do that with the curses library.

2) silent mode: scorer will run as a simple daemon which will send notifications from the background. But there is slight problem here. How will we know which match the user wants the notification for? To get over this problem I was thinking if we can add an option like --find-match-id on the command line which can be run like this:
``scorer --find-match-id``
Which is return a list of all the matches along with some matchId. 
Next we can add an option like --match-id where the user can pass it on the command line to get updates for that particular matchId like this:
``scorer --match-id 123434 [other options]``

What you think?

**Comment by talatshaikh29** [comment]
In my view, user configuration is always good if we are to target large and
diverse range of users

**Pull request merged**
