### PR TITLE
Added text to speech for scores 

### PR DESCRIPTION
**Pull request by kedarbramhe**

### CODE REVIEW

**Comment by neo1691** [comment]
This is nice, can you put all the code of pyttx into another module let say voice, and then import it in app.py? It wil be easy then to maintain the code, once we get in command line options into the code! 


Thanks!

**Comment by nirmalvp** [comment]
And Maybe a way to opt out of voice notifications if I don't want it to.?

**Comment by kedarbramhe** [comment]
@neo1691 Yes sure .. I will try to add more control over voice... @nirmalvp how about a command line argument?

**Comment by neo1691** [comment]
@kedarbramhe exactly, we are working out that. Just implement the voice notifications in a different module, I will add a command line switch to it when I implement argvparse!

**Comment by nirmalvp** [comment]
I am gonna shift all the json related code into a different module. Can you sync your development branch with the master?

**Comment by neo1691** [comment]
I already did that @nirmalvp

**Comment by nirmalvp** [comment]
@kedarbramhe Can you fix that before we merge it with the code? I think playing audio without a way to turn it off will be very intrusive. What do you say?

**Comment by kedarbramhe** [comment]
Yes I will try to make the changes tonight

**Comment by neo1691** [comment]
Just keep that module separate, I'll use argvparse and all a command line option. Just not getting the time now with a heavy work load. 

Sorry for the delay.

**Comment by kedarbramhe** [comment]
No problems. should I pull another request for that?

**Comment by neo1691** [comment]
No I think you can just modify the commits again.

**Comment by kedarbramhe** [comment]
Hi , I messed up while code rebasing . This was new to me , my fork was 69 commits old . Added the voice module anyway

**Comment by neo1691** [comment]
@kedarbramhe Hi, thanks a lot. I see you haven't called your API from the app.py? Any special reasons behind it?

**Comment by kedarbramhe** [comment]
I can add that but I have not yet thought of way to opt out of voice other than command line argument . Any ideas?

**Comment by neo1691** [comment]
@kedarbramhe Just integrate your voice code with app.py. I will add the command line arguments, and then unless the user won't ask for a voice, he won't get it. 

I won't be merging your code unless I test it and first implement command line options in ``master`` first.

**Comment by kedarbramhe** [comment]
There are still some changes I would like to add to voice.py like changing the age and gender of the voice , they are not working as of now . I will add them later.

**Comment by neo1691** [comment]
If something is not working, you would consider closing this pull request for now.!!

**Pull request closed without merging**
