### PR TITLE
making logger as separate entity instead of getting instance in every class

### PR DESCRIPTION
**Pull request by harsham4026**
@neo1691 this PR addresses the making logger as a separate class and using the same logger in every class we use. Previously we were importing the logger in every class and getting the instance of that. Now I made logger kind of global which we can import in all the classes and use. Please review the PR and let me know the changes if any.

### CODE REVIEW

**Comment by harsham4026** [comment]
@neo1691 Made the logger as global instead of getting the instance and formatting in every class. please review the changes.

**Comment by harsham4026** [comment]
@neo1691 I feel making a logger class global and using it every where would be nice instead of formatting or so... Please let me know your comments.

**Comment by harsham4026** [comment]
@neo1691 addressed the issue "logging changes #57"

**Review by an00bhav — CHANGES_REQUESTED** [review]
This PR implements the logging module and also at the same time, it implement's the notification system by removing `pynotify` module and introducing an external call to `notify-send`. 

I think one pr should only tackle one issue/feature. Can you revert back the changes you made to `notification.py`?

**Comment by an00bhav** [comment]
@harsham4026 Can you tell me what is the motivation of doing this, compared to what we were doing before?

**Comment by harsham4026** [comment]
@neo1691 previously we were not formatting the logger. In only one class you formatted and in rest of the we didn't. So thought of formatting in one class and using it every where else. Isn't it a good idea?

**Comment by harsham4026** [comment]
@neo1691 for the conflicts you are saying, shall I remove the logger things I added or what changes need to be made there?

**Comment by an00bhav** [comment]
@harsham4026 we made the logger instance in `app.py` using `scorer.app`. In the other modules we didn't had to format the logger instance as calling any logger with `scoere.*` will return a parent logger. 

`Multiple calls to logging.getLogger('someLogger') return a reference to the same logger object.`


https://docs.python.org/2/howto/logging-cookbook.html

**Comment by an00bhav** [comment]
@harsham4026 I don't think using a method in another module just for the logger instance is the best approach to implement the logging module across the app.

**Comment by harsham4026** [comment]
@neo1619 let's remove the logger function which I added then.

**Comment by harsham4026** [comment]
@neo1691 made the changes to notification.py. Are you gonna close this PR?

**Comment by an00bhav** [comment]
Yes, I think we will close this PR too. I feel sorry that you already wrote a lot of code, but let's discuss about the Issues on GitHub before you begin to start implementing some feature.

**Pull request closed without merging**
