### PR TITLE
UI support for the scorer app

### PR DESCRIPTION
**Pull request by nirmalvp**
Added UI support to the app.
Now, the user can select from the app using arrow keys instead of the using text input. This also avoids the need of input vaidation

Changes:
    Added a file ui.py
    Modified app.py to accomodate the new user input mechanism

scorer

### CODE REVIEW

**Comment by neo1691** [comment]
Hey thanks a lot. I am travelling this weekend. I'll most probably have a chance to look at the PR tomorrow. Thanks again.

**Comment by nirmalvp** [comment]
No problems. As usual, test it on python 3 :)

**Comment by neo1691** [comment]
Just reached home, will take a look at the code tomorrow!! 
Just as a sidnote, I am thinking of sticking to only python2 now for development, as it is becoming more and more difficult to maintain the code that supports both the versions of python! 

Any comments?

**Comment by neo1691** [comment]
Hi @nirmalvp , your code works well with python2, but fails with python3 because of inconsistent use of indentation levels. Even if I decide to use python2 for the project, I would still like the other developers to use 4 levels of spaces for a tab. Can you change your editor settings to use 4 spaces for tab instead of 8 and submit me the PR again? 

Thanks.

**Comment by nirmalvp** [comment]
I have fixed the indentation errors and now sticking on to the 4space indentation

**Comment by neo1691** [comment]
@nirmalvp Thanks a lot. I have migrated the project to python2. What's the status of this pull request? I see you have closed this now?

**Comment by nirmalvp** [comment]
I have made the changes but it shows merge conflicts. Any idea why?

**Comment by neo1691** [comment]
@nirmalvp Because I have made a lot of changes to the branch. Checkout the latest code in my structureCode branch. I will have to manually resolve the conflicts. Let's see if I can do that.

**Pull request merged**
