### PR TITLE
Jsonparsing

### PR DESCRIPTION
**Pull request by nirmalvp**
Added support to get live updates from the JSON file
Changes
-----------
File : fetch_scores

1. Matches now return only the team names in title without run information . Eg : Aus 312/4 vs NZ 122/2* will now be printed only as "AUS vs NZ" in user selection menu

2. getJsonURL(matchID) fn added which will return the full json url when a matchID is provided

3. getPlayingTeamNames(jsonurl) fn added which will return a {teamID:teamName} dictionary of the id and name of the two teams playing

4.getLastestScore() will now take jsonurl and the playingTeamNames dict as the object.
	--jsonData.get("live").get("innings") contains all the score info.
	--jsonData.get("live").get("innings") contains a "batting_team_id" and "bowling_team_id" which can be looked up against playingTeamNames{} to get the team name from team ID
	-- We will return both the score and the title where title will be "Batting Team name" vs "Bowling Team Name"

File : app.py

1. fs.getMatchID(int(matchChoice-1), xml) returns to a new variable to increase readablity
2. Added a call to getPlayingTeamNames(jsonurl) which will store the teamID->teamName mapping of the teams playing. This can be used to determine the batting and bowling sides later from the json object.

### CODE REVIEW

**Comment by neo1691** [comment]
This looks really really good. I was wondering how to get the score information from the json, preventing any potential hardcoding that breaks the code. I will test this code asap. 

I am trying to restructure the code in different modules and trying to make use of the python standard __main__.py and __init__.py. Do you have any experience with these files?

**Comment by nirmalvp** [comment]
You can move the files into folders and create a __init_.py file within folders you cant to be considered as modules.

**Comment by nirmalvp** [comment]
I did a round of testing today while a few matches were going on. The xml lists the set of matches that are scheduled for the day but  when the matches have yet not started, jsonData.get("live").get("innings") will fail since jsonData.get("live") is empty until the matches start. I have modified the code, to check for this condition and to notify the user about the game status. Will send you a pull request today

**Comment by nirmalvp** [comment]
I guess we have to live with some of the hardcoding for json parsing. How about a different .py file which will contain all the hardcoded constants?

**Comment by neo1691** [comment]
Let's merge this code first and make it work. @nirmalvp Can you add a try catch to the fetchLatestScores function so that we can handle the key error for "live"? And send a graceful error code that the match hasn't started yet? 

I will then merge it. I don't want to make that change myself, because I think you may lose the commit authority. I am not sure though, so better you only make the change!

**Comment by nirmalvp** [comment]
Rather than sending the error code, we can notify the user about the status of the game( Ex : "Game Scheduled to start at 09:00 IST" , "Team X has won the Toss and elected to bat") . So, we would loop like normal, keep sending these notifications after every nth second. When the matches start, the notification  jsonData.get("live") would start to contain data, and then we can start notifying the score. Don't you think this would be a better way ?

**Comment by neo1691** [comment]
Yes ofcourse that would be a much much better way!! Good thinking. I will add it in the todos!!

**Comment by nirmalvp** [comment]
I have already implemented it. Let me send you another pull request

**Comment by neo1691** [comment]
@nirmalvp before sending a PR, make sure you do a ``git fetch upstream`` and merge my changes. I have had one commit after merging your changes!!

**Pull request merged**
