### PR TITLE
Interrupt

### PR DESCRIPTION
**Pull request by nirmalvp**
Updated app.py with more error checks and alternate handling of Interupts. Added a new file "system.py" which contains a fn() that will print a goodbye message and then exit the app

Changes
--------

1. If No Live matches are available, notify the user and exit the app rather than giving him a selection menu
2. Provided a quit option in selection menu
3. User input is  now taken as raw_input . This fixes a type conversion error if user provides any non-digit
4. Logging moved down after validation since matches[matchChoice-1] could lead to exception for unvalidated match choices.
5. The infinite loop is applied only to the notify portion of the code. This ensures that the user selection screen is not provided to the user again unless he issues a keyboard interrupt.

### CODE REVIEW

**Comment by neo1691** [comment]
Hi @nirmalvp . Thanks a lot for the pull requests. This really looks good. I'll do some testing both on python2 as well as python3 and see if the code is working properly. 

As you can see, we are trying to write the script such that the script runs without any issues on both python2 as well as python3. Can you just confirm if the raw_input() function runs on python3? I am not sure, and I haven't really run the script with your PR. 

I will test it if I get time today, else I will have to test it from home. 

Thanks again.

**Comment by neo1691** [comment]
@nirmalvp This code breaks on python3! Are you only testing for python2?

**Comment by nirmalvp** [comment]
@neo1691 This should work with python3. I'd appreciate if you could check the changes on python3 . I run only 2.7 on my system

**Comment by neo1691** [comment]
@nirmalvp I have merged the code, however I have found two bugs pertaining to python3. I am not sure why I want the script to support both python 2 as well as python 3, and maybe in future revisions we might completely drop one of them. 

In findMatchesAvailable() from fetch_scores.py, you have are returning a map. And map in python3 are not subscript-able. You cannot use [i] notation to access it anymore. We can use list comprehensions but I have changed the map to a list in the findMatchesAvailable() function, which solves the issue. 

http://stackoverflow.com/questions/6800481/python-map-object-is-not-subscriptable

Taking about raw_input, this function was changed to input() in python3, I don't know if there has been any other implementation changes to that function, but there should be no difference in using input() / raw_input() since both are supported by python2 as only one is supported by python3. You just don't need to explicitly convert anything to a particular type like we used to do with raw_input(). So what we can do is, we can validate user's input once we get it to make sure that the input is correct. 

http://stackoverflow.com/questions/6800481/python-map-object-is-not-subscriptable

I will fix both the bugs introduced because of this merge, and this bugs are quite negligible to be honest. The code is really good now. Thanks for the PR's!

**Pull request merged**
